"""Added yelpID to EventRating class

Revision ID: 2b61b75f2306
Revises: 81af0793d9ec
Create Date: 2024-03-23 22:31:19.370695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b61b75f2306'
down_revision = '81af0793d9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yelpID', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_rating', schema=None) as batch_op:
        batch_op.drop_column('yelpID')

    # ### end Alembic commands ###