"""empty message

Revision ID: 2ba97bb9ceab
Revises: 550f9372b73c
Create Date: 2024-03-09 23:28:30.991530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba97bb9ceab'
down_revision = '550f9372b73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('friend 1', sa.Integer(), nullable=False),
    sa.Column('friend 2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend 1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['friend 2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('friend 1', 'friend 2')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('friends')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friends', sa.VARCHAR(length=1000), nullable=True))

    op.drop_table('friends')
    # ### end Alembic commands ###
