"""add event datetime

Revision ID: 550f9372b73c
Revises: 
Create Date: 2024-02-23 02:22:14.392252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550f9372b73c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_datetime')

    # ### end Alembic commands ###
