"""empty message

Revision ID: e97a4022d77d
Revises: 2ba97bb9ceab
Create Date: 2024-03-21 17:58:58.485574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97a4022d77d'
down_revision = '2ba97bb9ceab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=5000), nullable=True),
    sa.Column('friend', sa.String(length=5000), nullable=True),
    sa.Column('status', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['friend'], ['user.email'], ),
    sa.ForeignKeyConstraint(['user'], ['user.email'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('friend 1', sa.INTEGER(), nullable=False),
    sa.Column('friend 2', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friend 1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['friend 2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('friend 1', 'friend 2')
    )
    op.drop_table('status')
    # ### end Alembic commands ###
